# Generated by Django 6.0.3 on 2026-04-06 09:41

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickUpPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=255, verbose_name='Адрес')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='Местоположение')),
                ('work_schedule', models.TextField(verbose_name='График работы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('visits_count', models.IntegerField(default=0, verbose_name='Посещений')),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Рейтинг пункта')),
            ],
            options={
                'verbose_name': 'Пункт приема',
                'verbose_name_plural': 'Пункты приема',
            },
        ),
        migrations.CreateModel(
            name='PointWasteTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('is_actual_price', models.BooleanField(blank=True, default=True, null=True, verbose_name='Актуально')),
            ],
            options={
                'verbose_name': 'Приём отхода в пункте',
                'verbose_name_plural': 'Приёмы отходов в пунктах',
            },
        ),
    ]
