# Generated by Django 6.0.3 on 2026-04-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('points', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='is_moderated',
            field=models.BooleanField(default=False, verbose_name='Прошел модерацию'),
        ),
        migrations.AddField(
            model_name='pickuppoint',
            name='moderation_status',
            field=models.CharField(choices=[('new', 'Новый'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
