# Generated by Django 6.0.3 on 2026-04-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('active', 'Активна'), ('blocked', 'Заблокирована')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='user',
            name='points_visited_count',
            field=models.IntegerField(default=0, verbose_name='Всего посещено пунктов'),
        ),
    ]
