# Generated by Django 6.0.3 on 2026-04-18 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='waste_types/')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_types.measureunit')),
            ],
            options={
                'verbose_name': 'Тип отхода',
                'verbose_name_plural': 'Типы отходов',
            },
        ),
    ]
